sudo: required
services:
  - docker

jobs:
  include:
     - stage: Build Docker Image
       script:
       - docker build -t sirasaoa/build-android .

    - stage: Run Tests
      script:
      - docker run -it sirasaoa/build-android 

      after_success:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - docker push sirasaoa/build-android
            
    # - stage: Deploy Release Archive
    #   script:
    #   - docker run -e CI=true -v "$PWD":/app sirasaoa/build-android ./gradlew clean assembleRelease
    #   addons:
    #     artifacts:
    #       paths:
    #         - $PWD/app/build/outputs/apk/release/*.apk
