sudo: required
services:
  - docker

jobs:
  include:
    - stage: Build Docker Image
      script:
      - docker build -t sirasaoa/build-android .

    - stage: Run Tests
      script:
      - docker run -it -e CI=true -v "$PWD":/app sirasaoa/build-android ./gradlew clean assembleDebug

      after_success:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - docker push sirasaoa/build-android
            
    - stage: Deploy Release Archive
      script:
      - docker run -it -e CI=true -v "$PWD":/app sirasaoa/build-android ./gradlew clean assembleRelease
      - cp ./app/build/outputs/apk/release/*.apk .

      deploy:
        provider: s3
        region: us-east-1
        bucket: "travis-app-demo"
        access_key_id: "$ACCESS_KEY_ID"
        secret_access_key: "$SECRET_ACCESS_KEY"
        skip_cleanup: true
        glob: "*.apk"
