sudo: required
services:
  - docker

before_install:
  docker build -t sirasaoa/build-android . 

script:
  ./scripts/run_docker_android.sh ./scripts/compile.sh

after_success:
  #Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push image to Docker Hub
  - docker push sirasaoa/build-android
  