sudo: required
services:
  - docker

before_install:
  docker build -t sirasaoa/build-android . 

script:
  docker run -it -e CI=true -v "$PWD":/app sirasaoa/build-android \
  /bin/bash -c "./gradlew clean assembleDebug; cd app/build/outputs/apk/debug | ls -l" 

after_success:
  #Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push image to Docker Hub
  - docker push sirasaoa/build-android
  