sudo: required
services:
  - docker

before_install:
  docker build -t sirasaoa/build-android . 

script:
  docker run -e CI=true -w /home/gradle sirasaoa/build-android gradle -PdisablePreDex clean 

after_success:
  #Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push image to Docker Hub
  - docker push sirasaoa/build-android
  
