sudo: required
services:
  - docker

jobs:
  include:
    - stage: Build Docker Image
      script:
      - docker build -t sirasaoa/build-android .

    - stage: Run Tests
      script:
      - docker run -e CI=true sirasaoa/build-android ./gradlew clean assembleDebug 
      after_success:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - docker push sirasaoa/build-android

    - stage: Build Release Archive
      script:
      - docker run -e CI=true sirasaoa/build-android ./gradlew clean assembleRelease
